// Code generated by Slice Machine. DO NOT EDIT.
import { defineAsyncComponent } from 'vue';
import { defineSliceZoneComponents } from '@prismicio/vue';

export const components = defineSliceZoneComponents({
  // Slices will be registered here by Slice Machine
});
